// ID is the name of the file in '/i/emoticon/'

export const emoticon = [
  { id: 'AhiAsher', label: 'Ahi Asher', ext: 'png' },
  { id: 'AhiEstelle', label: 'Ahi Estelle', ext: 'png' },
  { id: 'AhiKai', label: 'Ahi Kai', ext: 'png' },
  { id: 'AimiCry', label: 'Ai.Mi Cry', ext: 'png' },
  { id: 'AiMiFree', label: 'Ai.Mi Free', ext: 'png' },
  { id: 'AiMiHello', label: 'Ai.Mi Hello', ext: 'gif' },
  { id: 'AiMiJam', label: 'Ai.Mi Jam', ext: 'gif' },
  { id: 'AiMiLaser', label: 'Ai.Mi Laser', ext: 'png' },
  { id: 'AiMiNOM', label: 'Ai.Mi N O M', ext: 'png' },
  { id: 'AiMiNoted', label: 'Ai.Mi Noted', ext: 'gif' },
  { id: 'AiMiPat', label: 'Ai.Mi Pat', ext: 'png' },
  { id: 'AiMiSmug', label: 'Ai.Mi Smug', ext: 'png' },
  { id: 'AiMiSpaceCat', label: 'Ai.Mi Space Cat', ext: 'png' },
  { id: 'AsherCheer', label: 'Asher Cheer', ext: 'png' },
  { id: 'AsherDisgust', label: 'Asher Disgust', ext: 'png' },
  { id: 'AsherPog', label: 'Asher Pog', ext: 'png' },
  { id: 'AsherYikes', label: 'Asher Yikes', ext: 'gif' },
  { id: 'DJAtlas', label: 'Atlas DJ', ext: 'gif' },
  { id: 'AtlasLfg', label: 'Atlas LFG', ext: 'png' },
  { id: 'AtlasNice', label: 'Atlas Nice', ext: 'png' },
  { id: 'AtlasPray', label: 'Atlas Pray', ext: 'png' },
  { id: 'AtlasSip', label: 'Atlas Sip', ext: 'png' },
  { id: 'AtlasThink', label: 'Atlas Think', ext: 'png' },
  { id: 'BlobBisexual', label: 'Blob Bisexual', ext: 'png' },
  { id: 'BlobLesbian', label: 'Blob Lesbian', ext: 'png' },
  { id: 'BlobPride', label: 'gay blob', ext: 'png' },
  { id: 'BlobTrans', label: 'Blob Trans', ext: 'png' },
  { id: 'Colin', label: 'dotColin', ext: 'png' },
  { id: 'DefaultThumbsUp', label: 'Default', ext: 'png' },
  { id: 'DojoAimi', label: 'Dojo Aimi', ext: 'png' },
  { id: 'DojoDubu', label: 'Dojo Dubu', ext: 'png' },
  { id: 'DojoMako', label: 'Dojo Mako', ext: 'png' },
  { id: 'DrekarBlahBlah', label: 'Drekar Blah Blah', ext: 'png' },
  { id: 'DrekarHeadpat', label: 'Drekar Headpat', ext: 'png' },
  { id: 'DrekarThink', label: 'Drekar Think', ext: 'png' },
  { id: 'DrexPog', label: 'Drex Pog', ext: 'png' },
  { id: 'DubuCheeky', label: 'Dubu Cheeky', ext: 'png' },
  { id: 'DubuCheerWEBP', label: 'Dubu Cheer', ext: 'gif' },
  { id: 'DubuConcern', label: 'Dubu Concern', ext: 'png' },
  { id: 'DubuHUH', label: 'DubuHUH', ext: 'png' },
  { id: 'DubuLetsGo', label: 'Dubu LFG', ext: 'gif' },
  { id: 'DubuNOM', label: 'DubuNom', ext: 'png' },
  { id: 'DubuOne', label: 'Dubu One', ext: 'png' },
  { id: 'DubuWhat', label: 'Dubu What', ext: 'png' },
  { id: 'EraBocchi', label: 'Era Bocchi', ext: 'png' },
  { id: 'EraRaindropSad', label: 'Era Raindrop', ext: 'png' },
  { id: 'EraShy', label: 'Era Shy', ext: 'png' },
  { id: 'EraSorry', label: 'Era Sorry', ext: 'png' },
  { id: 'EraWiltedPoppy', label: 'Era Wilted Poppy', ext: 'png' },
  { id: 'EstelleFacepalm', label: 'Estelle Facepalm', ext: 'png' },
  { id: 'EstelleOho', label: 'Estelle Oho', ext: 'png' },
  { id: 'EstelleRose', label: 'Estelle Rose', ext: 'png' },
  { id: 'FiniiBonk', label: 'Finii Bonk', ext: 'gif' },
  { id: 'FiniiCocoa', label: 'Finii Cocoa', ext: 'png' },
  { id: 'FiniiGrin', label: 'Finii Grin', ext: 'png' },
  { id: 'FiniiSmug', label: 'Finii Smug', ext: 'png' },
  { id: 'TeaTimeFini', label: 'Finii TeaTime', ext: 'png' },
  { id: 'FiniiTeehee', label: 'Finii Teehee', ext: 'png' },
  { id: 'FiniiTired', label: 'Finii Tired', ext: 'png' },
  { id: 'FiniiWheeze', label: 'Finii Wheeze', ext: 'png' },
  { id: 'FiniiZoom', label: 'Finii Ogey', ext: 'png' },
  { id: 'FrostfireTeamTsumTsum', label: 'Frostfire Team Tsum Tsum', ext: 'png' },
  { id: 'GardenerAtlas', label: 'Gardener Atlas', ext: 'png' },
  { id: 'JulietteAyaya', label: 'Juliette Ayaya', ext: 'png' },
  { id: 'JulietteComfy', label: 'Juliette Comfy', ext: 'png' },
  { id: 'JulietteCopium', label: 'Juliette Copium', ext: 'png' },
  { id: 'JulietteCryge', label: 'Juliette Cryge', ext: 'png' },
  { id: 'JulietteEz', label: 'Juliette Ez', ext: 'png' },
  { id: 'JuliettePointalt', label: 'Juliette Point', ext: 'png' },
  { id: 'JulietteThumbsUp', label: 'Juliette ThumbsUp', ext: 'png' },
  { id: 'JulietteVibe', label: 'Juliette Vibe', ext: 'png' },
  { id: 'JunoAgent', label: 'Juno Agent', ext: 'png' },
  { id: 'JunoBlankStare', label: 'Juno Annoyed', ext: 'png' },
  { id: 'JunoHappy', label: 'Juno Happy', ext: 'png' },
  { id: 'JunoLul', label: 'Juno Laugh', ext: 'png' },
  { id: 'JunoPopcorn', label: 'Juno Popcorn', ext: 'png' },
  { id: 'JunoSleep', label: 'Juno Sleep', ext: 'png' },
  { id: 'JunoStraw', label: 'Juno Straw', ext: 'png' },
  { id: 'JunoWahhh', label: 'Juno Wahhh', ext: 'png' },
  { id: 'JunoWOW', label: 'Juno WOW', ext: 'png' },
  { id: 'KaiChristmasExpansion', label: 'Kai Christmas', ext: 'png' },
  { id: 'KaiFine', label: 'Kai Fine', ext: 'png' },
  { id: 'KaiShrug', label: 'Kai Shrug', ext: 'png' },
  { id: 'KaiSmirk', label: 'Kai Smirk', ext: 'png' },
  { id: 'KasanDotingBrother', label: 'Kazan Doting', ext: 'png' },
  { id: 'KasanLosinIt', label: 'Kazan Losin It', ext: 'png' },
  { id: 'LunaCalculated', label: 'Luna Calculated', ext: 'gif' },
  { id: 'LunaCry', label: 'Luna Cry', ext: 'png' },
  { id: 'LunaGlasses', label: 'Luna Glasses', ext: 'png' },
  { id: 'LunaGoodJob', label: 'Luna Good Job', ext: 'png' },
  { id: 'LunaPeace', label: 'Luna Peace', ext: 'png' },
  { id: 'LunaWizardOrb', label: 'Luna Wizard', ext: 'png' },
  { id: 'MakoBadHairDay', label: 'Mako Bad Hair Day', ext: 'png' },
  { id: 'MakoCheers', label: 'Mako Cheers', ext: 'png' },
  { id: 'MakoDango', label: 'Mako Dango', ext: 'png' },
  { id: 'MakoHomeRun', label: 'Mako Home Run', ext: 'png' },
  { id: 'MakoOhno', label: 'Mako Ohno', ext: 'png' },
  { id: 'Mely', label: 'Mely', ext: 'png' },
  { id: 'NaoCheer', label: 'Nao Cheer', ext: 'png' },
  { id: 'NaoRest', label: 'Nao Rest', ext: 'png' },
  { id: 'NaoUnamused', label: 'Nao Unamused', ext: 'png' },
  { id: 'OactaviaYawn', label: 'Oactavia Yawn', ext: 'gif' },
  { id: 'OctaviaCheers', label: 'Octavia Cheers', ext: 'png' },
  { id: 'OctaviaRun', label: 'Octavia Run', ext: 'png' },
  { id: 'OctaviaShrug', label: 'Octavia Shrug', ext: 'png' },
  { id: 'RasmusBusiness', label: 'Rasmus Business', ext: 'png' },
  { id: 'RasmusCoffee', label: 'Rasmus Coffee', ext: 'png' },
  { id: 'RasmusLockIn', label: 'Rasmus Lock In', ext: 'png' },
  { id: 'RasmusMail', label: 'Rasmus Mail', ext: 'png' },
  { id: 'RuneCry', label: 'Rune Cry', ext: 'png' },
  { id: 'RuneDespair', label: 'Rune Despair', ext: 'png' },
  { id: 'RuneFeelRelieved', label: 'Rune Relieved', ext: 'png' },
  { id: 'RuneHeart', label: 'Rune Heart', ext: 'png' },
  { id: 'RuneCreepy', label: 'Rune Obscura', ext: 'png' },
  { id: 'RunePoor', label: 'Rune Poor', ext: 'png' },
  { id: 'RuneSurprised', label: 'Rune Surprised', ext: 'gif' },
  { id: 'RuneV', label: 'Rune V', ext: 'png' },
  { id: 'SoniiPepega', label: 'Sonii Pepega', ext: 'png' },
  { id: 'SoniiSalute', label: 'Sonii Salute', ext: 'png' },
  { id: 'SoniiTank', label: 'Sonii Tank', ext: 'png' },
  { id: 'SoniiTrophy', label: 'Sonii Trophy', ext: 'png' },
  { id: 'SoniiWires', label: 'Sonii Wires', ext: 'png' },
  { id: 'SoniiWTank', label: 'Sonii W Tank', ext: 'png' },
  { id: 'RockOniBleh', label: 'Vyce Bleh', ext: 'png' },
  { id: 'VyceCheers', label: 'Vyce Cheers', ext: 'png' },
  { id: 'VyceDrake2', label: 'Vyce Drake', ext: 'png' },
  { id: 'VyceHolidayStar', label: 'Vyce Holidays', ext: 'png' },
  { id: 'VyceRockOn', label: 'Vyce Rock On', ext: 'gif' },
  { id: 'VyceSweat', label: 'Vyce Sweat', ext: 'png' },
  { id: 'XDemonHours', label: 'X Demon Hours', ext: 'gif' },
  { id: 'XFleX', label: 'X FleX', ext: 'png' },
  { id: 'XGigaChad', label: 'X GigaChad', ext: 'png' },
  { id: 'XRead', label: 'X Read', ext: 'png' },
  { id: 'SummerX', label: 'X Summer', ext: 'png' },
  { id: 'XWheeze', label: 'X Wheeze', ext: 'png' },
  { id: 'ZentaroCryMask', label: 'Zentaro Cryge', ext: 'png' },
  { id: 'ZentaroDeadge', label: 'Zentaro Deadge', ext: 'png' }
];
